### ISSUE TITLE
Error trying to publish to npm

### ISSUE THREAD

**Issue by JavierCane** [CodelyTV/vue-skeleton#4]
I am trying to publish the package with `npm publish --access public`, however, it return me the following output:

```shell
$ npm publish --access public

npm notice
npm notice 📦  @codelytv/vue-skeleton@0.1.0
npm notice === Tarball Contents ===
npm notice 6.8kB README.md
npm notice 2.0kB package.json
npm notice === Tarball Details ===
npm notice name:          @codelytv/vue-skeleton
npm notice version:       0.1.0
npm notice filename:      @codelytv/vue-skeleton-0.1.0.tgz
npm notice package size:  2.9 kB
npm notice unpacked size: 8.9 kB
npm notice shasum:        4c2a0b2a692bbf93b167a5d09b1fef5383204a49
npm notice integrity:     sha512-VxBwOXlKRYFgr[...]RuTQrtx4w8+MQ==
npm notice total files:   2
npm notice
npm notice Publishing to https://registry.npmjs.org/
npm ERR! code E429
npm ERR! 429 Too Many Requests - PUT https://registry.npmjs.org/@codelytv%2fvue-skeleton

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/javiercane/.npm/_logs/2023-04-04T16_34_46_017Z-debug-0.log
```

Here you have the complete log:

```shell
$ cat /Users/javiercane/.npm/_logs/2023-04-04T16_34_46_017Z-debug-0.log

0 verbose cli /opt/homebrew/Cellar/node@16/16.20.0/bin/node /opt/homebrew/opt/node@16/bin/npm
1 info using npm@8.19.4
2 info using node@v16.20.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 0ms
5 timing config:load:file:/opt/homebrew/Cellar/node@16/16.20.0/lib/node_modules/npm/npmrc Completed in 2ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/Users/javiercane/Code/work/codely/public/npm-packages/vue-skeleton/.npmrc Completed in 1ms
10 timing config:load:project Completed in 3ms
11 timing config:load:file:/Users/javiercane/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/opt/homebrew/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:credentials Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 8ms
19 timing npm:load:configload Completed in 8ms
20 timing npm:load:mkdirpcache Completed in 0ms
21 timing npm:load:mkdirplogs Completed in 0ms
22 verbose title npm publish
23 verbose argv "publish" "--access" "public"
24 timing npm:load:setTitle Completed in 2ms
25 timing config:load:flatten Completed in 2ms
26 timing npm:load:display Completed in 2ms
27 verbose logfile logs-max:10 dir:/Users/javiercane/.npm/_logs
28 verbose logfile /Users/javiercane/.npm/_logs/2023-04-04T16_34_46_017Z-debug-0.log
29 timing npm:load:logFile Completed in 2ms
30 timing npm:load:timers Completed in 0ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 14ms
33 verbose publish [ '.' ]
34 silly logfile start cleaning logs, removing 1 files
35 silly logfile done cleaning log files
36 notice
37 notice 📦  @codelytv/vue-skeleton@0.1.0
38 notice === Tarball Contents ===
39 notice 6.8kB README.md
39 notice 2.0kB package.json
40 notice === Tarball Details ===
41 notice name:          @codelytv/vue-skeleton
41 notice version:       0.1.0
41 notice filename:      @codelytv/vue-skeleton-0.1.0.tgz
41 notice package size:  2.9 kB
41 notice unpacked size: 8.9 kB
41 notice shasum:        4c2a0b2a692bbf93b167a5d09b1fef5383204a49
41 notice integrity:     sha512-VxBwOXlKRYFgr[...]RuTQrtx4w8+MQ==
41 notice total files:   2
42 notice
43 notice Publishing to https://registry.npmjs.org/
44 http fetch PUT 429 https://registry.npmjs.org/@codelytv%2fvue-skeleton 70257ms attempt #3
45 timing command:publish Completed in 70300ms
46 verbose stack HttpErrorGeneral: 429 Too Many Requests - PUT https://registry.npmjs.org/@codelytv%2fvue-skeleton
46 verbose stack     at /opt/homebrew/Cellar/node@16/16.20.0/lib/node_modules/npm/node_modules/npm-registry-fetch/lib/check-response.js:95:15
46 verbose stack     at processTicksAndRejections (node:internal/process/task_queues:96:5)
46 verbose stack     at async publish (/opt/homebrew/Cellar/node@16/16.20.0/lib/node_modules/npm/node_modules/libnpmpublish/lib/publish.js:43:12)
46 verbose stack     at async otplease (/opt/homebrew/Cellar/node@16/16.20.0/lib/node_modules/npm/lib/utils/otplease.js:4:12)
46 verbose stack     at async Publish.exec (/opt/homebrew/Cellar/node@16/16.20.0/lib/node_modules/npm/lib/commands/publish.js:120:7)
46 verbose stack     at async module.exports (/opt/homebrew/Cellar/node@16/16.20.0/lib/node_modules/npm/lib/cli.js:78:5)
47 verbose statusCode 429
48 verbose pkgid @codelytv/vue-skeleton@0.1.0
49 verbose cwd /Users/javiercane/Code/work/codely/public/npm-packages/vue-skeleton
50 verbose Darwin 22.4.0
51 verbose node v16.20.0
52 verbose npm  v8.19.4
53 error code E429
54 error 429 Too Many Requests - PUT https://registry.npmjs.org/@codelytv%2fvue-skeleton
55 verbose exit 1
56 timing npm Completed in 70327ms
57 verbose code 1
58 error A complete log of this run can be found in:
58 error     /Users/javiercane/.npm/_logs/2023-04-04T16_34_46_017Z-debug-0.log
```

The only similar issue I have found is [this one](https://github.com/npm/cli/issues/805#issuecomment-714862567) recommending to change the package name. Due to this being something related to what is happening to us, what do you think about trying to change it? Any suggestions? something such as `vue-skeleton-loader`?

**Comment by antoniogiroz** [comment]
I've fixed the Publish workflow, including the Build step before running the tests, which it's been failing.

About the package name, I've tried to search for a package with the same name but it doesn't exist, so I'm not sure that's the reason. Anyway, we could rename as the original package `vue-loading-skeleton`. What do you think?

**Comment by JavierCane** [comment]
awesome!

yup, it would be great to rename it to `vue-loading-skeleton` because this way it would not be ambiguos with the other kind of application skeletons or templates 😊

Would you like to do the package rename, or would you prefer to do it by us?

🤟
